### ISSUE TITLE
License

### ISSUE THREAD

**Issue by jwerle** [littlstar/axis#58]

**Comment by jwerle** [comment]
cc @bnunez @tmugavero @humanshell

**Comment by humanshell** [comment]
am I cc'd cause u wanna know my input on what license to use?

**Comment by humanshell** [comment]
I say got with MIT or BSD. Short simple and uncomplicated.

**Comment by jwerle** [comment]
Maybe GPL ?

**Comment by humanshell** [comment]
To the best of my knowledge we would go with GPL if we want to ensure the code in this repo remains visible to the world no matter what future project may use it. Any use/re-distribution would require this code to remain open to the public under the GPL.

MIT and/or BSD would allow anyone to use this code in a project that could be closed source.
