### ISSUE TITLE
Index.html references build/build.css and build/build.js that don't exist

### ISSUE THREAD

**Issue by fluidpixel** [littlstar/axis#63]
should they be:
index.css & index.js?

**Comment by stephenmathieson** [comment]
no, `build/*` are built files.  they're built with `make`.

@jwerle any reason `index.html` doesn't point to `dist/*`?

**Comment by jwerle** [comment]
@stephenmathieson @fluidpixel they are pointing to `build/*` because we are testing with the development builds. They offer source maps to make debugging much easier. `index.html` is more or less a playground for testing... We should probably change that :)

**Comment by stephenmathieson** [comment]
makes sense ;)
