### ISSUE TITLE
Documentation on enabling mouse movement to pan video?

### ISSUE THREAD

**Issue by wadehammes** [littlstar/axis#65]
Right now you have to click to move video, I would like to be able to pan the video to the right if mousing to the right, and vice versa. I see a Pointer control in the index.html but that hides the cursor, and can't figure out how to get the cursor to stay but have the panning effect. Any help is appreciated!

**Comment by jwerle** [comment]
@wadehammes try `frame.controls.movement.enable();`

**Comment by wadehammes** [comment]
@jwerle thanks! Still not working though. Everything works but the mouse panning...here is my JS:

```
/*
* Initial AXIS element
*/
var frame = new Axis(document.querySelector('#video'), {
  src: '/wp-content/themes/base/library/video.mp4',
  crossorigin: true,
  resizable: true,
  preload: true,
  autoplay: true,
  muted: true,
  width: window.innerWidth,
  height: window.innerHeight,
  loop: true
});

// Render the video player
frame.render();

// Once Rendered, set up environment
frame.once('ready', function () {
  frame
  .focus()
  .seek(5)
  .play()
  .projection('equilinear')
  .rotate('y', {value: 0.01, every: 200})
  .controls.movement.enable();
});
```

Any thoughts? I also tried to move the `.controls.movement.enable()` out to its own line like `.render()` with no such luck. No console errors.

**Comment by jwerle** [comment]
@wadehammes oops! Try disabling the mouse too with `frame.controls.mouse.disable();`

**Comment by wadehammes** [comment]
@jwerle still nothing unfortunately. You can view my sandbox here: http://experius.com/video-test/

I really appreciate the help, seems like it's probably something dead simple.

**Comment by wadehammes** [comment]
Actually it appears to work but only when you click, is there an easy way to adapt this to hover?

**Comment by jwerle** [comment]
@wadehammes are you tying to take control of the mouse? Do you want the orientation to change *without* clicking?

**Comment by wadehammes** [comment]
I just want to be able to pan around the video while hover on the left or right sides of the screen - like seen here: https://www.felixandpaul.com/?projects/intro

**Comment by jwerle** [comment]
@wadehammes ah I see! That is currently not supported. However, we'd happily accept a PR if you'd like to contribute. Pointer lock is likely the best way to get the functionality you seek out of the box.
