### ISSUE TITLE
instal failed

### ISSUE THREAD

**Issue by aelmahalawey** [littlstar/axis#67]
when running component install littlstar/axis , it stops with two fatal errors: 
1- Error: ENOENT: no such file or directory, unlink '/Users/ahmedelmahalawey/Documents/Work/Web Applications/360PlayerGameApp/Axis/components/littlstar/axis/1.20.7.tar.gz'

2- fatal : no remote found for dependency "juliangruber/stream".

please help me with this issue as soon as possible I believe that axis is very promising and could be my final choice.

**Comment by jwerle** [comment]
@aelmahalawey Try using a different package manager. We haven't used component for some time and it may not work properly anymore. Axis is available through npm as well as the package name `littlstar-axis`

**Comment by SKCingleVue** [comment]
Could you please update the README file to reflect the new installation method?

**Comment by aelmahalawey** [comment]
I used npm install littlstar-axis and it worked fine but the sample code available on the readme didn't work so I used the code available in index.html available under the repo and it worked, what I think is the problem is frame.play() should be frame .render() instead.
