### ISSUE TITLE
can not use custom mp4 file

### ISSUE THREAD

**Issue by areshero** [littlstar/axis#79]
I used the demo code in the index.html, it works with the src file from little star. However when I change the source to my vr mp4 files, it gives me an error:

axis.js:1155 Uncaught (in promise) DOMException: The element has no supported sources.Axis.play @ axis.js:1155Axis.onclick @ axis.js:586cb @ axis.js:43266

what might be the cause?

**Comment by areshero** [comment]
I downloaded the web.mp4 and put it on my server, it still gave me the same error: no supported sources

**Comment by jwerle** [comment]
@areshero axis supports playback of an mp4 from anywhere so long as your browser does not impose CORS restrictions and/or your server respects CORS headers. how are you serving `index.html` ?
