### ISSUE TITLE
standard

### ISSUE THREAD

**Issue by stephenmathieson** [littlstar/axis#87]
i've given up on linting/"my" code-style and have been using [standard](https://github.com/feross/standard) for everything lately. it's helpful to have a linter setup for obvious reasons, and defining our own rules just seems like a waste of time.

also, it's annoying to switch back-and-forth between code "styles". i'd rather just give in and do what a good portion of the community is doing anyway.

thoughts @jwerle?

**Comment by jwerle** [comment]
I like this idea. There isn't any standard for the project and we
definitely need one
