### ISSUE TITLE
Play video in reverse

### ISSUE THREAD

**Issue by tunic** [littlstar/axis#99]
Is there a simple way to play the video in reverse?
thanks

**Comment by stephenmathieson** [comment]
no, not at the moment. i don't think it's planned to add this either.

do you have a compelling reason you need to play 360 video in reverse?

/cc @jwerle

**Comment by tunic** [comment]
i cannot give away the details, but it would be useful in a game scenario
if you think it's possible, could you point me to the part of the code that would need to be changed?
thanks

**Comment by jwerle** [comment]
@tunic you can emulate reverse playback with an animation frame loop and setting the current time with `frame.time(frame.time() - someDeltaValue`

**Comment by jwerle** [comment]
Closing as this is not intended to be supported
